export const AD_LIST_REQUEST = 'AD_LIST_REQUEST'
export const AD_LIST_SUCCESS = 'AD_LIST_SUCCESS'
export const AD_LIST_FAIL = 'AD_LIST_FAIL'

export const AD_DETAILS_REQUEST = 'AD_DETAILS_REQUEST'
export const AD_DETAILS_SUCCESS = 'AD_DETAILS_SUCCESS'
export const AD_DETAILS_FAIL = 'AD_DETAILS_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const AD_DELETE_REQUEST = 'AD_DELETE_REQUEST'
export const AD_DELETE_SUCCESS = 'AD_DELETE_SUCCESS'
export const AD_DELETE_FAIL = 'AD_DELETE_FAIL'

export const AD_CREATE_REQUEST = 'AD_CREATE_REQUEST'
export const AD_CREATE_SUCCESS = 'AD_CREATE_SUCCESS'
export const AD_CREATE_FAIL = 'AD_CREATE_FAIL'
export const AD_CREATE_RESET = 'AD_CREATE_RESET'

export const AD_UPDATE_REQUEST = 'AD_UPDATE_REQUEST'
export const AD_UPDATE_SUCCESS = 'AD_UPDATE_SUCCESS'
export const AD_UPDATE_FAIL = 'AD_UPDATE_FAIL'
export const AD_UPDATE_RESET = 'AD_UPDATE_RESET'